version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/
    steps:
      - checkout
      - run:
          name: phplint env setup
          command: |
            sudo npm i -g phplint
            phplint "php-redis/*.php"
  # setup-eks:

workflows:
  default:
    jobs:
      - build-frontend: #checkout php, lint php
          filters:
            branches:
              only: [circleci-project-setup]
      # - setup-eks #eks setup