version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install php
          command: |
            sudo apt install php
            echo php -v
      - run:
          name: phplint env setup
          command: |
            sudo npm i -g phplint
      - run:
          name: check phplint
          command: |
            ./phplint.sh
      - run:
          name: success
          when: on_success
          command: |
            echo 'success php lint'
      - run:
          name: fail
          when: on_fail
          command: |
            echo 'php lint failed'

  setup-eks:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: check progress
          command: |
            echo 'php lint passing'


workflows:
  default:
    jobs:
      - build-frontend: #checkout php, lint php
          filters:
            branches:
              only: [circleci-project-setup]
      - setup-eks: #eks setup
          requires: [build-frontend]